### ISSUE TITLE
Do not change viewpoint when setting new routes

### ISSUE THREAD

**Issue by patsonluk** [patsonluk/airline#127]
> when creating a new route the map jumps to the departure airport. do you think it'd be maybe better to not jump the viewport? it makes it a little hard when looking for the best destination airport around a zone

**Comment by PMarxen** [comment]
I think it would be better to not jump!

**Comment by oxford1223334** [comment]
This should be high priority. It's just annoying when it jump back to our hub especially if we are setting long range/intercontinental route or to medium/small size airport where we need to zoom in..

**Comment by patsonluk** [comment]
Deployed to production. Please force refresh ur browser to ensure the JS is updated
