### ISSUE TITLE
Pull requests...

### ISSUE THREAD

**Issue by DeltaJets** [patsonluk/airline#177]
Not to be pushy, I understand you might not have time, etc., but I was wondering if you could tell me when to expect [some of] my pull requests to be merged. I don't want to seem disrespectful.

**Comment by patsonluk** [comment]
kekeke sry...usually over the weekend. Depending on the weather...if it's good weather i will likely be outdoor.

I will probably be doing more coding soon due to the bad winter weather here lol

**Comment by DeltaJets** [comment]
Ok. Thanks!
