### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by acokeaday** [patsonluk/airline#267]
While following steps
installed mysql-server ( version 5 )
installed default-java-jre

ran ./activator publishLocal

error message after running ./activator run  -> Selection MainInit

`Id is 1
0 generated user CPT
[error] (run-main-0) java.sql.SQLException: Incorrect string value: '\xC5\x82aw -...' for column 'name' at row 1
[error] java.sql.SQLException: Incorrect string value: '\xC5\x82aw -...' for column 'name' at row 1
[error]         at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
[error]         at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
[error]         at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
[error]         at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
[error]         at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
[error]         at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551)
[error]         at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
[error]         at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
[error]         at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
[error]         at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094)
[error]         at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
[error]         at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:1449)
[error]         at com.patson.data.AirlineSource$.$anonfun$saveAirlines$1(AirlineSource.scala:124)
[error]         at scala.collection.immutable.List.foreach(List.scala:312)
[error]         at com.patson.data.AirlineSource$.saveAirlines(AirlineSource.scala:121)
[error]         at com.patson.init.AirlineGenerator$.$anonfun$generateAirlines$3(AirlineGenerator.scala:62)
[error]         at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:190)
[error]         at com.patson.init.AirlineGenerator$.generateAirlines(AirlineGenerator.scala:46)
[error]         at com.patson.init.AirlineGenerator$.mainFlow(AirlineGenerator.scala:31)
[error]         at com.patson.init.MainInit$.delayedEndpoint$com$patson$init$MainInit$1(MainInit.scala:12)
[error]         at com.patson.init.MainInit$delayedInit$body.apply(MainInit.scala:8)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error]         at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error]         at scala.App.$anonfun$main$1(App.scala:75)
[error]         at scala.App.$anonfun$main$1$adapted(App.scala:75)
[error]         at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
[error]         at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:904)
[error]         at scala.App.main(App.scala:75)
[error]         at scala.App.main$(App.scala:73)
[error]         at com.patson.init.MainInit$.main(MainInit.scala:8)
[error]         at com.patson.init.MainInit.main(MainInit.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] stack trace is suppressed; run last Compile / bgRun for the full output
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 60 s, completed Feb 4, 2020, 2:19:14 PM
`

**Comment by acokeaday** [comment]
So even i hit the error, i was able to run the game, following the rest of the steps. not sure if this is something that will affect the running of the game.

**Comment by jandro4321** [comment]
add character_set_server=utf8mb4 to your /etc/my.cnf and restart mysql.  it's a unicode characters issue, see https://stackoverflow.com/questions/10957238/incorrect-string-value-when-trying-to-insert-utf-8-into-mysql-via-jdbc

**Comment by patsonluk** [comment]
Thanks! adding to instruction
