### ISSUE TITLE
V2: Runway requirement

### ISSUE THREAD

**Issue by patsonluk** [patsonluk/airline#316]
Instead of a airport class categorize by capacity, we want to have a more "gradual" approach.

Each aircraft should have a runway requirement (in meter) and match against the airports

For airport, we actually already have runway data

Any helper please? :)

**Comment by patsonluk** [comment]
@matittner Any interesting in lending me some help for V2 please? ;)

**Comment by Edoebzd** [comment]
Hi, I think you should use https://ourairports.com/data/ (Updated versions of airports.csv and runways.csv) as the source for airports runway length, if you need help I can try to write a parser for that data.

**Comment by patsonluk** [comment]
Ya it's a good idea to update the files :)

I think our existing V1 version is already using files from that website so we shouldn't need to rewrite any code logic ;)

**Comment by Edoebzd** [comment]
Hi, I am writing to let you know that airplane runway requirements data is almost ready to be added, we will create a commit within 16 hours from now. The data has been collected by me (Air Italy), CSA, and ForeverAir.

**Comment by patsonluk** [comment]
@Edoebzd That sounds great!

V2 is coming along nicely and there's a slight chance we might start early alpha this coming weekend, so the new airplane runway data would come in handy!

**Comment by FrankPigeon** [comment]
I hope the data is all right and correctly uploaded. Please let us know if you need any help with V2.
Regards, CSA
