### ISSUE TITLE
V2: Cannot buy airplane if balance under original price, but higher than discounted price

### ISSUE THREAD

**Issue by Edoebzd** [patsonluk/airline#321]
![image](https://user-images.githubusercontent.com/38160197/101768549-fce94580-3ae5-11eb-9532-5d5b9615bc87.png)

This bug might be present also in v1 (Not checked)

**Comment by patsonluk** [comment]
yep probably a v1 bug too :) thanks! i will take a note later!

**Comment by patsonluk** [comment]
Cannot reproduce the problem, what does it say when u hover over the disabled purchase button please?

**Comment by Edoebzd** [comment]
The standard "Not enough money" message (I can't remember the exact message, if you want I can try to reproduce it again)

**Comment by Edoebzd** [comment]
Edit: seems fixed now (on v2)
