### ISSUE TITLE
V2: Airport runways values not corresponding

### ISSUE THREAD

**Issue by Edoebzd** [patsonluk/airline#323]
![image](https://user-images.githubusercontent.com/38160197/101893011-6cbe0580-3ba4-11eb-8a39-6ab47bf9dfb5.png)
Here this airport is shown with a 750m runway

But in the airport details page a 600m runway is shown
![image](https://user-images.githubusercontent.com/38160197/101893081-87907a00-3ba4-11eb-8bec-fa0f6837d629.png)

**Comment by Edoebzd** [comment]
I've made a script to check the in-game runway data and compare it with the runways.csv file, and I found 309 airports with wrong values. Here is the list https://pastebin.com/nUkhqV7q

The list is a result of the comparison between the 4k airports returned by the javascript function getAirports() of the game (it calls the api) and the airports.csv/runways.csv included in the v2 branch of the code.

If you need them in a csv/json file I can generate it.
There are also 311 airports without runways, we have a list also of them and we will try to find all the relevant data.

**Comment by Edoebzd** [comment]
It might be because ICAO codes of airports do not always correspond between the airport database and the runway database, despite being for the same airport. I'll try to find more information about this, and hopefully also a fix.

**Comment by patsonluk** [comment]
> It might be because ICAO codes of airports do not always correspond between the airport database and the runway database, despite being for the same airport. I'll try to find more information about this, and hopefully also a fix.

OOOO
just noticed that they actually use a unique ID for airport <-> runway
lemme fix the script

**Comment by patsonluk** [comment]
And i know why Dallas Love Field is not there, cause the logic currently only accept airports with name "Airport". I remember back then if i dun do that it will include whole bunch of military bases.

I will code something to mitigate that

**Comment by patsonluk** [comment]
kk Same goes for Reus Air Field too...at least that's the name in the CSV file

**Comment by patsonluk** [comment]
Closing this issue, the runway not matching airport is a limitation for airports that with no runway data or short runway. We simply pad it to min of 750m so it can at least fly some airplanes :)
