### ISSUE TITLE
V2: Base marker and Airport marker both present at the same airport

### ISSUE THREAD

**Issue by Edoebzd** [patsonluk/airline#324]
![image](https://user-images.githubusercontent.com/38160197/101903859-389f1080-3bb5-11eb-9b4e-f9cc06d08bde.png)
![image](https://user-images.githubusercontent.com/38160197/101903877-3f2d8800-3bb5-11eb-9169-aef6566ac5f3.png)

**How to reproduce:** Zoom in/out on the map near your airport, it's somewhat random which one of the two is displayed
**Expected behaviour:** I think only the base marker (yellow) needs to be there

I don't know if it's only a problem of gateway airports or all airports are affected by this bug

**Comment by patsonluk** [comment]
Closing as I don't see that anymore
