### ISSUE TITLE
V2: route frequency limit not working

### ISSUE THREAD

**Issue by Edoebzd** [patsonluk/airline#333]
The 30 (or more with alliance bonus) weekly flights limit per route is not being applied. If this is how it's supposed to be, remove from the benefits of alliances the "increase weekly frequency", since it wouldn't make sense.
![image](https://user-images.githubusercontent.com/38160197/101987555-0238c280-3c95-11eb-97fa-2b4f93a4c054.png)

**Comment by patsonluk** [comment]
@Edoebzd i think it's not going to apply. Going to think about other ways to make alliance rewarding - the plan is to make the relationship system more delicate

For example some negotiation bonus for top alliances

relationship bonus for other alliance member if ur airline is national etc

**Comment by patsonluk** [comment]
i will update the alliance bonus page once i really figure out what bonues make sense. Thanks for reporting!

**Comment by patsonluk** [comment]
Actually, there's still a "soft cap" at 30, it gets increasingly difficult if u want to break that.

Though, I think we want to remove the alliance bonus on it, too overpowered imho

Updated UI to reflect that.

Thanks
