### ISSUE TITLE
V1/V2: Passenger map showing other weeks data if link has no data for the selected week

### ISSUE THREAD

**Issue by Edoebzd** [patsonluk/airline#334]
If a link has some data for a previous week, but no data for the current week the link is not on the map, but if you hover with the mouse where it should be you see the popup like if there was an actual link

Week 10
![image](https://user-images.githubusercontent.com/38160197/101993819-f0b7e080-3cbd-11eb-905e-ed41faea1f8f.png)

Week 9
![image](https://user-images.githubusercontent.com/38160197/101993856-0fb67280-3cbe-11eb-87bb-bbfa7ab6eb42.png)

Edit: bug also present in V1

**Comment by patsonluk** [comment]
Good catch!

Fixed in https://github.com/patsonluk/airline/commit/9becb45f2fc437ace677c5c89fc7f3dee3edda86
