### ISSUE TITLE
Out of date instructions

### ISSUE THREAD

**Issue by Techmokid** [patsonluk/airline#419]
Hello!

I have noticed that the instructions for how to set up the server is completely out of date and don't work. I've created a set of instructions with images that outline how to create your own server that actually work. Hope this helps
 
[Instructions for getting airline server running.docx](https://github.com/patsonluk/airline/files/6409315/Instructions.for.getting.airline.server.running.docx)

**Comment by Rhettung** [comment]
Can you explain how to fix map issue? :)

**Comment by Techmokid** [comment]
Huh, interesting. I forgot to include that part. Gimme a bit to remember how I fixed that one and I'll get back to you as soon as I can!

**Comment by Rhettung** [comment]
Hi, I´ve managed it by myself. Thanks for your afford. I have one more question. Did you install the master release or the v2 version? I have tried it with v2 and now unfortunately have the problem that apparently the database is not complete although the scripts have all run cleanly. However, for example, the table airport runway is completely empty and I can not find the error.

**Comment by Techmokid** [comment]
I have only done it with v1. I've not tried setting up a v2 server yet

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by patsonluk** [comment]
> Hi, I´ve managed it by myself. Thanks for your afford. There is one html file which delivers another maps API and has to be edited. I have one more question. Did you install the master release or the v2 version? I have tried it with v2 and now unfortunately have the problem that apparently the database is not complete although the scripts have all run cleanly. However, for example, the table airport runway is completely empty and I can not find the error.

Ah thanks for reporting that. I have fixed it for the initalization.

If u have the world generated already, u can simply run `GeoDataPatcher` and it should fix it too :)
