### ISSUE TITLE
Enhancement proposal: Retain airport names when moving between Research and Ticket tabs

### ISSUE THREAD

**Issue by t288msd** [patsonluk/airline#487]
When researching a new route users often move between the Research and Ticket tabs. This is usually done for the same airport pair, eg JFK-LHR. Proposed enhancement is to retain the airport pair when moving between the two tabs rather than having to type them in again

<img width="1440" alt="Screenshot 2022-01-03 at 08 10 40" src="https://user-images.githubusercontent.com/67978025/147889577-9f7a03b1-7f3c-48ec-89bb-80f593c2b2e1.png">

**Comment by BWBama85** [comment]
Second this. Would be a nice QoL improvement.

**Comment by Bohaska** [comment]
I would also like this!

**Comment by patsonluk** [comment]
Implemented in 2.1
