### ISSUE TITLE
Alliance identification feature

### ISSUE THREAD

**Issue by t288msd** [patsonluk/airline#489]
In the smaller alliances, members change frequently. This proposal easily identifies your alliance partners when building new routes and looking at existing routes. Proposal is to highlight alliance partner names in a different colour on the following screens (as per the screenshots with crude markup) 

User story:
As an alliance member
I want to easily identify my alliance partners when building new routes and looking at existing routes
So that I don't compete against them and can see where we are and aren't working well together

![Screenshot 2022-01-03 at 10 51 07](https://user-images.githubusercontent.com/67978025/147892939-b9e8063e-1c1d-49de-857e-a0f29a8b0236.jpg)

![Screenshot 2022-01-03 at 10 52 40](https://user-images.githubusercontent.com/67978025/147892948-a35d4bb6-e5ad-4440-8a7c-66bcbf0e0ea6.jpg)

**Comment by patsonluk** [comment]
Thanks for the suggestion. A feature that addresses this is implemented in https://github.com/patsonluk/airline/pull/491
