### ISSUE TITLE
V2.1: Build issue

### ISSUE THREAD

**Issue by southworst** [patsonluk/airline#495]
When running "MainInit" on the v2.1 branch i get the following error:

Finished generating pool of 1000000
..........10% ..........20% ..........30% ..........40% ..........50% ..........60% ..........70% ..........80% ..........90% ..........100% [error] (run-main-0) java.lang.ArithmeticException: / by zero
[error] java.lang.ArithmeticException: / by zero
[error]         at com.patson.init.GeoDataGenerator$.$anonfun$generateAirportData$17(GeoDataGenerator.scala:342)
[error]         at scala.collection.immutable.List.map(List.scala:226)
[error]         at com.patson.init.GeoDataGenerator$.generateAirportData(GeoDataGenerator.scala:316)
[error]         at com.patson.init.GeoDataGenerator$.buildAirportData(GeoDataGenerator.scala:221)
[error]         at com.patson.init.GeoDataPatcher$.mainFlow(GeoDataPatcher.scala:39)
[error]         at com.patson.init.GeoDataPatcher$.delayedEndpoint$com$patson$init$GeoDataPatcher$1(GeoDataPatcher.scala:17)
[error]         at com.patson.init.GeoDataPatcher$delayedInit$body.apply(GeoDataPatcher.scala:11)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error]         at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error]         at scala.App.$anonfun$main$1(App.scala:75)
[error]         at scala.App.$anonfun$main$1$adapted(App.scala:75)
[error]         at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
[error]         at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:904)
[error]         at scala.App.main(App.scala:75)
[error]         at scala.App.main$(App.scala:73)
[error]         at com.patson.init.GeoDataPatcher$.main(GeoDataPatcher.scala:11)
[error]         at com.patson.init.GeoDataPatcher.main(GeoDataPatcher.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] stack trace is suppressed; run last Compile / bgRun for the full output

**Comment by patsonluk** [comment]
Thanks, it should be fixed in 2.1
