### ISSUE TITLE
error in MainInit on new deployment

### ISSUE THREAD

**Issue by southworst** [patsonluk/airline#557]
error when running MainInint on a brand-new instance of the game, similar/possibly related to issue 495

Finished generating pool of 1000000
..........10% ..........20% ..........30% ..........40% ..........50% ..........60% ..........70% ..........80% ..........90% ..........100% Deleted 0 airport records
[error] (run-main-0) java.sql.SQLException: No value specified for parameter 13
[error] java.sql.SQLException: No value specified for parameter 13
[error]         at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[error]         at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[error]         at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[error]         at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[error]         at com.mysql.jdbc.PreparedStatement.checkAllParametersSet(PreparedStatement.java:2268)
[error]         at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2248)
[error]         at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2115)
[error]         at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2070)
[error]         at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5187)
[error]         at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2055)
[error]         at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:1502)
[error]         at com.patson.data.AirportSource$.$anonfun$saveAirports$1(AirportSource.scala:630)
[error]         at com.patson.data.AirportSource$.$anonfun$saveAirports$1$adapted(AirportSource.scala:616)
[error]         at scala.collection.immutable.List.foreach(List.scala:312)
[error]         at com.patson.data.AirportSource$.saveAirports(AirportSource.scala:616)
[error]         at com.patson.init.GeoDataGenerator$.buildAirportData(GeoDataGenerator.scala:262)
[error]         at com.patson.init.GeoDataGenerator$.mainFlow(GeoDataGenerator.scala:58)
[error]         at com.patson.init.GeoDataGenerator$.delayedEndpoint$com$patson$init$GeoDataGenerator$1(GeoDataGenerator.scala:40)
[error]         at com.patson.init.GeoDataGenerator$delayedInit$body.apply(GeoDataGenerator.scala:34)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error]         at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error]         at scala.App.$anonfun$main$1(App.scala:75)
[error]         at scala.App.$anonfun$main$1$adapted(App.scala:75)
[error]         at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
[error]         at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:904)
[error]         at scala.App.main(App.scala:75)
[error]         at scala.App.main$(App.scala:73)
[error]         at com.patson.init.GeoDataGenerator$.main(GeoDataGenerator.scala:34)
[error]         at com.patson.init.GeoDataGenerator.main(GeoDataGenerator.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] stack trace is suppressed; run last Compile / bgRun for the full output

**Comment by patsonluk** [comment]
Fixed in https://github.com/patsonluk/airline/commit/234576f25a085216473d7e03bb38ab479a161f31
